### ISSUE TITLE
DHX fails to pick a unit as of juju 2.0 alpha-2

### ISSUE THREAD

**Issue by chuckbutler** [juju/plugins#63]
Looks like DHX was just hit by some of the API nuance changes as of 2.0-alpha2 (verifiable in the latest charmbox:dev, bootstrap a model controller, create a new model, deploy something, then attempt to attach via `juju dhx` )

```
ubuntu@dev:~$ juju dhx -r redmine/0
Traceback (most recent call last):
  File "/home/ubuntu/.juju-plugins/juju-dhx", line 328, in <module>
    unit_name, unit = choose_unit(args, opts)
  File "/home/ubuntu/.juju-plugins/juju-dhx", line 296, in choose_unit
    status = get_env(opts).status()
  File "/home/ubuntu/.juju-plugins/juju-dhx", line 182, in get_env
    get_env._env = jujuclient.Environment.connect(opts.env)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 534, in connect
    return Connector().run(cls, env_name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 132, in run
    jhome, data = self.parse_env(env_name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 224, in parse_env
    raise EnvironmentNotBootstrapped(env_name)
jujuclient.EnvironmentNotBootstrapped: Environment  is not bootstrapped
```

**Comment by johnsca** [comment]
The specific exception listed here is fixed in the newer jujuclient lib, but there were still issues that needed to be addressed in dhx.
